---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  macos:
    name: macos
    runs-on: macos-11
    env:
      CMAKE_OPTS: >-
        -DUSE_WERROR=ON
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DUSE_COMPILE_CACHE=ON
      CCACHE_MAXSIZE: 500M
      MAKEFLAGS: -j3
      DEVELOPER_DIR: /Applications/Xcode_11.7.app/Contents/Developer
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Cache ccache data
        uses: actions/cache@v3
        with:
          key: ccache-${{ github.job }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ github.job }}-${{ github.ref }}-
            ccache-${{ github.job }}-
          path: ~/Library/Caches/ccache
      - name: Install dependencies
        run: |
          brew install ccache fftw pkg-config libogg libvorbis lame libsndfile \
                       libsamplerate jack sdl libgig libsoundio lilv lv2 stk \
                       fluid-synth portaudio fltk qt@5 carla
          npm install --location=global appdmg
      - name: Set up tmate session
        uses: mxschmitt/action-tmate@53a5c23a925969671a6bb98ea70a4f650928ef93
      - name: Configure
        run: |
          mkdir build
          cmake -S . \
                -B build \
                -DCMAKE_INSTALL_PREFIX="../target" \
                -DCMAKE_PREFIX_PATH="$(brew --prefix qt5)" \
                $CMAKE_OPTS \
                -DUSE_WERROR=OFF
      - name: Build
        run: cmake --build build
      - name: Build tests
        run: cmake --build build --target tests
      - name: Run tests
        run: build/tests/tests
      - name: Package
        run: |
          cmake --build build --target install
          cmake --build build --target dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/lmms-*.dmg
      - name: Print ccache statistics
        run: |
          echo "[ccache config]"
          ccache -p
          echo "[ccache stats]"
          ccache -s
